server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: im-communication-system
  
  # 添加文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  web:
    resources:
      static-locations: classpath:/static/

  # --- 数据库配置 ---
  datasource:
    url: jdbc:mysql://localhost:3307/im_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- JPA配置 ---
  jpa:
    hibernate:
      # 使用validate模式，不允许JPA修改表结构
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': true
        # 指定数据库方言，适配 MySQL 8+ 版本
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    
  # --- Flyway数据库迁移配置 ---
  flyway:
    enabled: true
    # 迁移脚本位置
    locations: classpath:db/migration
    # 基线版本
    baseline-version: 1
    # 如果数据库不为空，是否自动执行基线
    baseline-on-migrate: true
    # 验证迁移脚本的校验和
    validate-on-migrate: true
    # 允许乱序迁移
    out-of-order: true
    # 清理数据库（生产环境请设为false）
    clean-disabled: true
    # 编码
    encoding: UTF-8
    # 表名前缀
    table: flyway_schema_history

  # --- Redis配置 ---
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  # --- 邮件配置 ---
  # 真实邮件发送配置 - 请根据您的邮箱服务商进行配置
  mail:
    # QQ邮箱配置示例
    host: smtp.qq.com
    port: 587
    username: 1012779129@qq.com        # 请替换为您的QQ邮箱
    password: tgduimgwozcxbbhi   # 请替换为您的QQ邮箱授权码（不是登录密码）
    
    # 163邮箱配置示例（注释掉的备选配置）
    # host: smtp.163.com
    # port: 465
    # username: your-email@163.com
    # password: your-authorization-code
    
    # Gmail配置示例（注释掉的备选配置）
    # host: smtp.gmail.com
    # port: 587
    # username: your-email@gmail.com
    # password: your-app-password
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          # 对于SSL连接（如163邮箱端口465），启用以下配置
          # ssl:
          #   enable: true
          #   trust: smtp.163.com
    default-encoding: UTF-8

  # --- Actuator ?????? (????) ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# --- JWT配置 ---
# JWT配置已移至app.jwt下

# --- 应用配置 ---
app:
  # JWT配置
  jwt:
    secret: im-communication-system-jwt-secret-key-2024-very-long-secure-key-for-hs512-algorithm-minimum-512-bits-required-abcdefghijklmnopqrstuvwxyz0123456789
    access-token-expiration: 86400  # 24小时（秒）
    refresh-token-expiration: 604800  # 7天（秒）
    temp-token-expiration: 300  # 5分钟（秒）
    token-prefix: "Bearer "
    header-name: Authorization
    issuer: im-communication-system
  
  # WebSocket配置
  websocket:
    # WebSocket认证配置
    auth:
      required: true  # 是否要求WebSocket连接必须认证
      allow-anonymous-in-dev: true  # 在开发环境中是否允许匿名连接
    
    # 连接设置
    connection:
      ping-interval: 30000  # 心跳包间隔（毫秒）
      max-idle-time: 600000  # 最大空闲时间（毫秒）
      max-connections-per-user: 3  # 每个用户允许的最大连接数
    
    # 消息配置
    message:
      max-text-message-size: 64000  # 最大文本消息大小（字节）
      max-binary-message-size: 1048576  # 最大二进制消息大小（字节）
      buffer-size: 8192  # 缓冲区大小（字节）
  
  # 验证码配置
  verification-code:
    default-length: 6
    default-expire-minutes: 5
    send-interval-seconds: 60
    max-retry-count: 5
    code-types:
      email-register:
        length: 6
        expire-minutes: 5
        prefix: "EMAIL_REG"
      email-login:
        length: 6
        expire-minutes: 5
        prefix: "EMAIL_LOGIN"
      password-reset:
        length: 6
        expire-minutes: 10
        prefix: "PWD_RESET"
      email-bind:
        length: 6
        expire-minutes: 5
        prefix: "EMAIL_BIND"
      phone-verify:
        length: 6
        expire-minutes: 5
        prefix: "PHONE_VERIFY"
      captcha:
        length: 4
        expire-minutes: 2
        prefix: "CAPTCHA"
      two-factor:
        length: 6
        expire-minutes: 10
        prefix: "TWO_FACTOR"
    security:
      enable-ip-limit: true
      max-send-per-hour: 10
      enable-complexity-check: false
  
  # 文件上传配置
  file-upload:
    upload-path: ./uploads
    base-url: http://localhost:8080
    max-file-size: 10485760  # 10MB
    max-request-size: 52428800  # 50MB
    allowed-image-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
    allowed-file-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - application/pdf
    image-compression:
      enabled: true
      quality: 0.85  # 提高压缩质量，减少损失
      max-width: 1920
      max-height: 1080
      max-file-size-for-compression: 2097152  # 2MB，小于此大小的文件不压缩
    avatar:
      size: 800
      default-avatar: /images/default-avatar.png
      directory: avatars
  
  # MinIO对象存储配置
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    default-bucket: im-files
    # 新的存储桶配置 - 按访问级别分类
    public-bucket: im-public-files
    private-bucket: im-private-files

  
  # 文件清理配置
  file:
    cleanup:
      enabled: true  # 是否启用定时清理
      daily-cleanup-days: 30  # 每日清理：删除30天前的软删除文件
      weekly-cleanup-days: 90  # 每周清理：删除90天前的软删除文件
    # 临时文件清理配置
    temporary-cleanup:
      enabled: true  # 是否启用临时文件清理
      default-expiration-days: 7  # 默认临时文件过期天数
      minio-lifecycle-enabled: true  # 是否启用MinIO生命周期规则
  
  # 数据一致性监控配置
  data-consistency:
    monitor:
      enabled: true
      auto-repair: true
      check-interval-hours: 1
    url-expire-seconds: 3600  # 1小时
    enable-https: false
    connect-timeout: 10000
    write-timeout: 60000
    read-timeout: 10000

# --- Elasticsearch配置 ---
elasticsearch:
  enabled: true  # 默认禁用Elasticsearch
  host: localhost
  port: 9200
  scheme: http
  connection-timeout: 5000
  socket-timeout: 30000


